version: '3.1'
services:
  node:
    build: 
      context: ./server
      dockerfile: ./server/Dockerfile
    environment:
      - NODE_ENV=production
    ports: 
      - 8080:8080
    depends_on: 
      - db
    links: 
      - db:database
  db:
    image: mariadb
    restart: always
    volumes: 
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: blog
    ports: 
      - 3306:3306
  
    
