version: '3.1'
services:
  node:
    build: 
      context: ./server
      dockerfile: ./Dockerfile-dev
    environment:
      - NODE_ENV=development
    volumes: 
      - ./server/src:/usr/src/app/src
    ports: 
      - 8080:8080
    depends_on: 
      - db
    links: 
      - db:database
  db:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    image: mariadb
    restart: always
    volumes: 
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: blog
    ports: 
      - 3306:3306
  
    
