version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes: 
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
    ports: 
      - 3306:3306
  node:
    build: ./server
    environment:
      - NODE_ENV=production
    ports: 
      - 8080:8080
      - 3306:3306
    
